test

diff --git a/.github/workflows/check-release.yml b/.github/workflows/check-release.yml
--- a/.github/workflows/check-release.yml
+++ b/.github/workflows/check-release.yml
@@ -18,28 +18,28 @@ jobs:
     - name: Check for existing version
       id: check_version
       run: |
-        CONFIG_FILE_PATH="src-tauri/ccv/tauri.conf.json";
+        CONFIG_FILE_PATH="src-tauri/ccv/tauri.conf.json"
         if [ ! -f ${CONFIG_FILE_PATH} ]; then
-            echo "${CONFIG_FILE_PATH} not found!";
-            exit 1;
+            echo "${CONFIG_FILE_PATH} not found!"
+            exit 1
         fi
         VERSION="$(jq -r .version ${CONFIG_FILE_PATH})"
         if [ -n "$(git tag -l "ccv-v${VERSION}")" ]; then
             echo "${VERSION} already exists. Please update version"
-            exit 1;
+            exit 1
         fi
         echo "version ${VERSION}"
         echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
     - name: Check for change log
       id: check_change_log
       run: |
-        VERSION="${{steps.check_version.outputs.version}}";
-        CHANGE_LOG_FILE_PATH="./change-log.json";
+        VERSION=${{steps.check_version.outputs.version}}
+        CHANGE_LOG_FILE_PATH="./change-log.json"
         if [ $(jq -r 'has("'${VERSION}'")' ${CHANGE_LOG_FILE_PATH}) == false ]; then
             echo "Change log for version ${VERSION} is not defined"
-            exit 1;
+            exit 1
         fi
-        CHANGE_LOG=$(jq -r '."'${VERSION}'" | if type=="array" then map("- " + .) | join("\n\r") else . end' ${CHANGE_LOG_FILE_PATH});
-        echo ${CHANGE_LOG};
-        echo "change_log=${CHANGE_LOG}" >> "$GITHUB_OUTPUT"
+        CHANGE_LOG=$(jq -r '."'${VERSION}'" | if type=="array" then map("- " + .) | join("\n\r") else . end' ${CHANGE_LOG_FILE_PATH})
+        echo ${CHANGE_LOG}
+        echo "change_log=\"${CHANGE_LOG}\"" >> "$GITHUB_OUTPUT"
   
